### ISSUE TITLE
Definición de Topics

### ISSUE THREAD

**Issue by barcia** [barcia/ngal#10]
Eu creo que podería ser boas idea definir os _topics_ que se poden usar, e usar só eses. 
* Senón, penso que vaise dar o caso de que moitos proxectos acaben tendo algún _topic_ que se nos ocorreu no momento, pero só se usa nese proxecto, e así perden un pouco a súa utilidade. 
* Ademáis, pódese dar o caso de que poñamos sinónimos ou cousas así.
* Que estén predifinidos, non quere decir que non se poidan engadir máis cada vez que vexamos que poden ser útiles.
* Se están predefinidos, pódense indicar tamén no schema e que se validen os YAML se só se usan _topics_ válidos.

**Comment by oscarotero** [comment]
Ok, non me parece mal. Como se engadirían máis? Habería un yaml coa lista de topics válidos?

**Comment by barcia** [comment]
Si, por exemplo. Ou poderíamos poñelos directamente no schema.json e así xa non habería que duplicalos.

**Comment by oscarotero** [comment]
Vale, tamén. Eu digo porque estou pensando en facelo o máis fácil posible para que a xente poida colaborar e meter aquí o contido. Pero podemos comezar poñéndoo directamente no schema e logo xa imos vendo.

**Comment by barcia** [comment]
Si, se eso pódese poñer tamén no README, aínda que xa estarían duplicados. Tal vez con sinalar que están nese arquivo sexa suficiente.

Eu, vendo o que temos ata o de agora, propoño estas, a ver qué opinas:

```yml
- deseño
- asmr
- videoxogos
- cultura
- axenda
- humor
- entrevistas
- musica
- moda
- infantil
```

Penso que ao mellor tamén pode encaixar un etiqueta como _random_ (ou un substituto en galego), non o sei.

* Aínda que hai varias que lle puxemos _galego_, ou _lingua_, ou algo así… non sei se esto será demasiado xenérico. Pode que ao mellor non teña moito sentido, pois a intención é que todos sexan en galego, e case seguro que é unha temática que tratan de xeito puntual a maioría, pero ningún de xeito exclusivo. 

* Algún proxecto como _Gabinete de curiosidades_ e _ladaíñas atlánticas_ a verdade é que non sei moi ben de qué van e qué etiquetas poderían encaixar. algo como _persoal_? _literatura_? _ensaio_?

**Comment by oscarotero** [comment]
Buf, é complexo. Eu fun metendo así o que puiden ver. Por exemplo, asmr é unha etiqueta que non creo que se use máis que para esa canle, xa que é moi específica. Eso pode pasar con outras temáticas. Quizáis etiquetas demasiado xenéricas acheguen pouco valor, e demasiado específicas fai que haxa unha listaxe enorme. Non sabería dicirche. Unha opción é deixalo libre por agora e máis adiante intentar unificar, se vemos que a cousa se desmadra.

Hai casos de xente que trata só do galego, ou é un contido importante na súa canle. Por exemplo olaxonmario ten moitos vídeos falando sobre o galego, o colonialismo lingüístico, etc. Ou os vídeos do dígocho eu...

En canto eses boletíns, si podería ser unha mestura de todo: persoal e ensaio. Pero bueno, hai moita cousa que é dificil de catalogar.

**Comment by barcia** [comment]
Si, non é sinxelo non. Pero bueno, tamén aínda que algunha só exista nun proxecto e pareza que non vai ter moito uso, se as poñemos xunto a cada proxecto tamén son útiles para que a xente vexa de forma rápida sobre qué vai ese proxecto
