### ISSUE TITLE
URL dos channels de YouTube e Twitch

### ISSUE THREAD

**Issue by barcia** [barcia/ngal#11]
Para unificar o tema dos channels, eu creo que tanto en YouTube como en Twitch (e en calquera outra) podemos facer como nas demáis canles e poñer só o nome de usuario ou ID, non? queda algo máis limpo todo e fai a mesma función.

![Captura de pantalla 2021-02-15 a las 21 57 58](https://user-images.githubusercontent.com/5719646/107992405-ee814380-6fd8-11eb-9158-c518b527391f.png)

**Comment by oscarotero** [comment]
Si, non é mala idea. Ademáis, en youtube necesitamos o id para xerar a url do feed, e así é un xeito de forzala, xa que non todas as urls de youtube inclúen ese id.
