### ISSUE TITLE
Activación de gh-page

### ISSUE THREAD

**Issue by oscarotero** [barcia/ngal#16]
Metin un workflow para publicar o sitio estático en github pages (bueno, realmente publicao no branch [gh-pages](https://github.com/barcia/ngal/tree/gh-pages)). Terías que activalo en Settings e que use ese branch como source.

Se prefires publicalo noutro sitio, tipo Varcel ou Netlify, tamén me vale. Fixeno así por rapidez.

**Comment by barcia** [comment]
Ok, perfecto 👍
