### ISSUE TITLE
Deno

### ISSUE THREAD

**Issue by barcia** [barcia/ngal#8]
@oscarotero, sobre o que comentas de Deno, non teño moita experiencia pero si o probei para ver como funcionaba e tal e gústame. Se ves que pode encaixar, usámolo sen problema.

De inicio fíxeno así porque o tiña con Next.js, e para que xa funcionara correctamente con Vercel.

Respecto a Deno teño algunhas dudas:
* En plataformas como Netlify ou Deno non funciona, ¿non? ¿Só teñen Node?
* Supoño que para a parte de Express, testing, etc. haberá alternativas ou que se poden usar os mesmos que con Node.

**Comment by oscarotero** [comment]
@barcia É só unha suxerencia, pero o que máis cómodo che resulte, que tampouco quero complicar a cousa :)
Comentábao tamén por se queres experimentar ou algo.

Eu para cousas persoais estou usando Deno para todo, porque me mola bastante. De feito ata creei un xerador de páxinas estáticas (o equivalente a 11ty ou jekyll, pero para Deno: https://github.com/lumeland/lume). E hai unha plantilla para crear o típico blog: https://github.com/lumeland/base-blog que, como ves no readme, funciona en GH Pages, Vercel, Netlify e Fleek (e supoño que noutros máis).
Esas plataformas non teñen Deno instalado, pero pódese instalar no propio comando de build.

En canto a backend, hai versións de Express para Deno (aquí unha busca rápida: https://deno.land/x?query=express) pero aí xa non teño tanta experiencia. Tamén podemos usar Node para iso. Incluso se poderían facer dous repositorios: un só para o contido (que só inclúa os yaml e xere os json, por exemplo) e outro para construír o sitio para navegar pola api, e aí xa se pode usar Express e toda a pesca. Non sei, como ti decidas, que eres o xefe :)

**Comment by barcia** [comment]
Pode ser unha opción. Se eso máis adiante pódese probar a cambiar, sen problema.

Si, teño botado un ollo ao repositorio de _lume_ e ten moi boa pinta! eu son moi fan de 11ty tamén. De feito, levo unhas semanas preparando uns cambios nunha das miñas webs e estiven moi tentado a probar _lume_, pero tamén é certo que sempre acabo perdendo o tempo probando cousas novas e despois nunca remato nada, así que ao final contívenme, jeje pero ten boa pinta si. De feito tiña ganas de mirar como resolves o tema de obter o contido, porque unha das pequenas pegas que lle atopo a 11ty é que as funcións que ten para xestioanr coleccións están demasiado orientadas a markdown. Para obter contido de unha api xa non é tan cómodo.

**Comment by oscarotero** [comment]
Acabo de subir un script de proba empregando Deno para recoller os datos:
https://github.com/barcia/ngal/blob/deno/scripts/build.js

Como podes ver, é moi sinxelo pero funciona bastante ben, para lanzalo no teu ordenador, só tes que executar:

```
deno run --allow-read --allow-net --allow-write scripts/build.js
```

Recolle a última entrada de calquera Feed RSS/Atom (con `loadFeed`) e fixen un caso especial para youtube (`loadYoutubeFeed`).

Dime que che parece.

**Comment by oscarotero** [comment]
Ben, creo que comentamos case ao mesmo tempo, jejeje.
En fin, que como vexas, podemos deixalo para máis adiante sen problemas.

E o de lume non fai falta usalo porque o fixera eu, eh? :D (de todos xeitos se algún día o queres probar, aqui me tes para o que precises).

**Comment by barcia** [comment]
Ah non! seu eu era porque pensaba que igual daba algo a lata… se xa o tes, xenial!!! 👍 a min a verdade é que tamén me ten moi boa pinta Deno, sobretodo polo tema da sintaxis e tal, e polo das dependencias… que hay veces que o _node_modules_ é o pozo sin fondo. 

Pois botolle un ollo, a ver se aprendo algo, e por min perfecto! graciñas!

**Comment by oscarotero** [comment]
Moi ben, pois bótalle un ollo ao que fixen e mira como o garda en `dist/api.json` e xa me contas. (realmente con Deno é moi cómodo traballar, xa verás como unha vez que comezas xa non vas querer volver a Node).

Aproveitando, creo que quizáis hai que unificar algunhas cousas de cada *channel*. Por exemplo, os podcasts inclúen directamente o feed, as canles de youtube inclúen a url, e outras cousas como as newsletters ou a web inclúen a url e o feed como subvalores.

**Comment by barcia** [comment]
Eu vexoo ben!!  teño algunha dúbida:

* Respecto a Deno, a min funcionoume porque eu xa o tiña instalado na miña máquina, pero senón entendo que petaría, ¿non? E relacionado con esto, vin no _base-blog_ de lume que para que funcione en plataformas como Netlify o que fas é descargalo en cada build, non?
* Paréceme xenial que YouTube teña un feed!! non o sabía!! eu estivera peleándome coa súa API. Así esto xa nos vale, e se Twitch ten algo parecido xa sería perfecto.
* Respecto ao que dis de unificar o dos _channels_, sí, eu opino o mesmo… claro, eu comentárao así pensando en que sería o contido final que saliría na API. Se se usa como recurso para recopilar o resto de información, tal vez haxa que modificar algo para que todo encaixe, tanto o YML como a info da API.
* Eu tamén tiña algunha cousa a maiores para comentar, pero mellor poñoas es issues independentes para que quede máis ordeada a conversa.

**Comment by oscarotero** [comment]
- Si, claro. Hay que instalalo (igual que tamén hai que instalar node). Unha vez instalado, simplemente tes que executar `deno upgrade` cando queiras actualizalo á última versión. Nas diferentes plataformas non ven pre-instalado por defecto (como sí está Node), pero pódese instalar por curl directamente. Se ves [o comando de Netlify](https://github.com/lumeland/base-blog/blob/master/netlify.toml#L3), primeiro instalo Deno con `curl | sh` e logo execútoo. En Netlify estan experimentando con [dar soporte a brew](https://community.netlify.com/t/now-in-experimental-alpha-homebrew-access-in-the-build-image/26074) co cal, poderíase ter un `Brewfile.netlify` cos paquetes necesarios para instalar, pero a última vez que probei non funcionaba moi ben e con curl sh funciona estupendamente (a idea pasouma [un tipo que ten un framework de Deno chamado Aleph.js](https://discord.com/channels/794537085641818124/794537086278828094/800012657745723432).
- Si, oxalá o tiveran todos :) (a ver o que tardan en quitalo)
- Moi ben. O formato do yaml seguramente haxa que ilo axustando segundo vaiamos metendo cousas.
- Perfecto
